# Generated by Django 6.1 on 2026-08-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='collaborations/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('research_collaborator', 'Research Collaborator'), ('research_assistant', 'Research Assistant'), ('junior_research_assistant', 'Junior Research Assistant'), ('alumni', 'Alumni')], max_length=50)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=300)),
                ('research_interest', models.TextField()),
                ('biography', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('orcid', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('current_affiliation', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(upload_to='lab_members/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='news/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('journal', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('doi', models.URLField(blank=True)),
                ('abstract', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(help_text='Example: 🧬', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('linkedin', models.URLField(blank=True)),
                ('orcid', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('photo', models.ImageField(upload_to='supervisor/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('future', 'Future Project')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researcharea')),
            ],
        ),
    ]
